name = "MyPack"
uuid = "17557c3b-80b6-4e17-9fe1-7f89207c9f94"
authors = ["Vasilis Tsilids"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
